server:
  port: 8010

spring:
  application:
    name: census-fwmt-rmadapter
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    user:
      name: "user"
      password: "password"

management:
  # Place /info and /health in the root
  endpoints.web.base-path: ''
  endpoint:
    health:
      show-details: always

logging:
  profile: DEV
  level:
    root: WARN
    uk.gov.ons.census.fwmt: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.amqp: INFO
    org.hibernate: INFO
    org.apache.commons.dbcp2: INFO
    org.springframework: INFO

rabbitmq:
  fwmt:
    username: "guest"
    password: "guest"
    hostname: "localhost"
    port: 5672
    virtualHost: "/"
  rm:
    username: "guest"
    password: "guest"
    hostname: "localhost"
    port: 5672
    virtualHost: "/rm"
  initialInterval: 5000
  multiplier: 3.0
  maxInterval: 45000
  concurrentConsumers: 5
  rmQueue: "RM.Field"
  rmDeadLetter: "RM.FieldDLQ"
  rmExchange: "adapter-outbound-exchange"

redis:
  host: "localhost"
  port: 6379
  password: "password"
  database: 0

equrl: https://fieldservice-ENV_NAME.census-gcp.onsdigital.uk/launch/