info:
  name: 'project.artifactId'
  version: 'project.version'
  origin: 'scm.url'
  commit: 'buildNumber'
  branch: 'scmBranch'
  built: 'timestamp'
  
server:
  port: 9094

spring:
  application:
    name: fwmt-job-uk.gov.ons.fwmt.fwmtrmadapter
  servlet:
    multipart:
      max-file-size: 12800MB
      max-request-size: 12800MB
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.amqp: INFO
    org.hibernate: INFO
    org.apache.commons.dbcp2: INFO
    org.springframework: INFO
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"

rabbitmq:
  rm:
    username: "guest"
    password: "guest"
    hostname: "localhost"
    port: 5672
    virtualHost: "/"
  fwmt:
    username: "guest"
    password: "guest"
    hostname: "localhost"
    port: 5672
    virtualHost: "/"
  initialinterval: 5000
  multiplier: 3.0
  maxInterval: 45000
