server:
  port: 9094


spring:
  application:
    name: fwmt-job-uk.gov.ons.fwmt.fwmtrmadapter
  http.multipart:
    max-file-size: 12800MB
    max-request-size: 12800MB
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  rabbitmq:
#    username: guest
#    password: guest
#    host: localhost
#    fwmt:
#      port: 5672
#    rm:
#      port: 6672
#    virtualhost: /

management.endpoint.health.show-details: always

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.apache.commons.dbcp2: ERROR
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"