spring:
  application:
    name: FWMT RM Adapter
  rabbitmq:
    username: ${cloud.services.rabbitmq.connection.username}
    password: ${cloud.services.rabbitmq.connection.password}
    host: ${cloud.services.rabbitmq.connection.host}
    port: ${cloud.services.rabbitmq.connection.port}
    virtualhost: ${cloud.services.rabbitmq.connection.virtualhost}