spring:
  application:
    name: FWMT RM Adapter

rabbitmq:
  rm:
    username: ${cloud.services.rm-rabbitmq.connection.username}
    password: ${cloud.services.rm-rabbitmq.connection.password}
    host: ${cloud.services.rm-rabbitmq.connection.host}
    port: ${cloud.services.rm-rabbitmq.connection.port}
    virtualhost: ${cloud.services.rm-rabbitmq.connection.virtualhost}
  fwmt:
    username: ${cloud.services.fwmt-rabbit.connection.username}
    password: ${cloud.services.fwmt-rabbit.connection.password}
    host: ${cloud.services.fwmt-rabbit.connection.host}
    port: ${cloud.services.fwmt-rabbit.connection.port}
    virtualhost: ${cloud.services.fwmt-rabbit.connection.virtualhost}
  initialinterval: 5000
  multiplier: 3.0
  maxInterval: 45000